/**
  @file
  @author  Fyodorov "bga" Alexander <bga.email@gmail.com>
 
  @section LICENSE
 
  Experimental common javascript RIA library http://github.com/bga/jbasis

  Copyright (c) 2009-2010, Fyodorov "Bga" Alexander <bga.email@gmail.com>
  All rights reserved.

  Redistribution and use in source and binary forms, with or without
  modification, are permitted provided that the following conditions are met:
      * Redistributions of source code must retain the above copyright
        notice, this list of conditions and the following disclaimer.
      * Redistributions in binary form must reproduce the above copyright
        notice, this list of conditions and the following disclaimer in the
        documentation and/or other materials provided with the distribution.
      * The name of the developer may not be used to endorse or promote
        products derived from this software without specific prior
        written permission.

  THIS SOFTWARE IS PROVIDED BY FYODOROV "BGA" ALEXANDER "AS IS" AND ANY EXPRESS OR
  IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
  IN NO EVENT SHALL FYODOROV "BGA" ALEXANDER BE LIABLE FOR ANY DIRECT, INDIRECT,
  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
  NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
  @section DESCRIPTION
*/

this.$jb.Loader._scope().
_require("$jb/OOP.js").
//_require("$jb/$jb.EventTarget.js").
//_require("$jb/$G.Function.js").
_require('$jb/exceptions.js').
_willDeclared("$jb/$jb.Net.Base.js").
_completed(function($G, $jb){

/** @namespace containts network io classes */
if($jb.Net == null)
  $jb.Net = {};

/** @class base class for all network io classes. Provide stream like interface */
$jb.Net.Base = Object(function()
{
  /** 
    @var {$jb.EventTarget.Base} event target for io operations 
    @event open {Function(
      this {ThisClass} <this>
      stream {ThisClass} <this>
    )} stream has opened
    @event data {Function(
      this {ThisClass} <this>
      stream {ThisClass} <this>
    )} stream has received data
    @event error {Function(
      this {ThisClass} <this>
      stream {ThisClass} <this>
      err {Any} error object
    )} stream has received data
    @event close {Function(
      this {ThisClass} <this>
      stream {ThisClass} <this>
    )} stream has closed 
    @event flush {Function(
      this {ThisClass} <this>
      stream {ThisClass} <this>
    )} stream has flushed. Event is generated by <ThisClass#_waitFlush>
  */
  this.eventTarget = null;
  
  /** @var {$jb.Net.ConnectionState} current connection state */
  this.connectionState = $jb.Net.ConnectionState.CLOSED;
});

$jb.Net.Base.name = '$jb.Net.Base';

/** @enum <$jb.Net.Base#connectionState> connection state of network io class instance */
if($jb.Net.ConnectionState == null)
  $jb.Net.ConnectionState = {};
  
/** @const stream is opening */
$jb.Net.ConnectionState.OPENING = 0;

/** @const stream opened */
$jb.Net.ConnectionState.OPENED = 1;

/** @const stream closed */
$jb.Net.ConnectionState.CLOSED = 2;

/** 
  @fn get received data
  @param dataFormat? {String} data format
  @return {String} reserved data
*/  
$jb.Net.Base.prototype._data = function(dataFormat)
{
  return null;
};

/**
  @fn send data to opened (<ThisClass#readyState> == <$jb.Net.ReadyState.OPENED>) stream
  @throw {InvalidStateError} if <ThisClass#readyState> != <$jb.Net.ReadyState.OPENED>
  @param data {String} data to send
  @return {ThisClass} <this>
*/  
$jb.Net.Base.prototype._send = function(data, dataFormat)
{
  if(this.readyState != $jb.Net.ReadyState.OPENED)
    throw new InvalidStateError('state must be <$jb.Net.ReadyState.OPENED>');
    
  return this;  
};

/**
  @fn check if stream is flushed
  @return {Boolean} true if flushed else false
*/  
$jb.Net.Base.prototype._isFlushed = function()
{
  return true;
};

/**
  @fn order <ThisClass#eventTarget#onFlush>
  @return {ThisClass} <this>
*/  
$jb.Net.Base.prototype._waitFlush = function()
{
  this._fireEvent('flush', this, [this]);
  
  return this;
};

/**
  @fn unorder <ThisClass#eventTarget#onFlush> ordered by <ThisClass#_waitFlush>
  @throw {InvalidStateError} if call count of <ThisClass#_waitFlush> less <ThisClass#_stopWaitFlush>
  @return {ThisClass} <this>
*/  
$jb.Net.Base.prototype._stopWaitFlush = function()
{
  return this;
};

/**
  @fn reopen stream
  @param isSilentClose {Boolean} {Optional} <false> mean fire <ThisClass#eventTarget#onClose>
  @return {ThisClass} <this>
*/  
$jb.Net.Base.prototype._reopen = function(isSilentClose)
{
  return this;
};

/**
  @fn close stream
  @param isSilentClose {Boolean} {Optional} <false> mean fire <ThisClass#eventTarget#onClose>
  @return {ThisClass} <this>
*/  
$jb.Net.Base.prototype._close = function(isSilentClose)
{
  return this;
};

});